### PR TITLE
Engine: font width of empty text should be zero

### LINKED ISSUE #1892: Text width of empty string with outline should be zero
**Describe the bug**
Text width of an empty string with automatic outline 1 value has changed in the specific test game attached from being 1 to now being 2, but it should be 0.

**AGS Version**
- AGS 3.6.0.7 has the previous **behavior (A)**
- Change happens in this commit https://github.com/adventuregamestudio/ags/commit/3a9b8f199e09b9919a201c1d2fa486a79761b339 
- AGS 3.6.0.8 and current 3.6.0.40 maintains the **behavior (B)**

**Game**
[TestWidth.zip](https://github.com/adventuregamestudio/ags/files/10377414/TestWidth.zip)

**To Reproduce**
1. Use GetTextWidth with a string that is empty `""` and use a font that has an outline set.
2. Alternatively, run the demo game above

**Expected behavior**
Text width for an empty string should be 0 regardless of outline size.

**Screenshots**
image
**behavior (A)** (AGS 3.6.0.7 and before, also current 3.5.1.23)

image
**behavior (B)** (AGS 3.6.0.8 and forward, including current 3.6.0.40)

**Desktop:**
 - OS: Windows
 - Version 10

**additional context**

Alternatively, we can also maintain previous behavior (compatibility) and fix this in a later version if it's too late to change this in 3.6.0.

### PR DESCRIPTION
**Pull request by ericoporto**
fix #1892

### CODE REVIEW

File: Engine/ac/global_gui.cpp [hunk 1]
```diff
@@ -167,6 +167,12 @@ int GetTextWidth(const char *text, int fontnum) {
   if ((fontnum < 0) || (fontnum >= game.numfonts))
     quit("!GetTextWidth: invalid font number.");
 
+  if(loaded_game_file_version < kGameVersion_360 &&
+     String_IsNullOrEmpty(text) &&
+     get_font_outline(fontnum) == FONT_OUTLINE_AUTO)
+  {
+    return game_to_data_coord(1);
```
Comment (ivan-mogilko) [inline Engine/ac/global_gui.cpp:174]: I don't think this fallback is necessary here, this is such a niche case, and I have doubts it was relied upon in some game's design. So I'd propose to not do this unless someone finds a game which gets broken by this fix.

Comment (ericoporto) [reply Engine/ac/global_gui.cpp:174]: That's fine, I will remove it :)

Comment (ericoporto) [reply Engine/ac/global_gui.cpp]: done, removed!
