### PR TITLE
Android: fix can't open vox packages in single game launcher

### LINKED ISSUE #1577: Android: can't play any sound in an external vox package in single game launcher
**Describe the bug**
Sounds not in the game main .ags package can't be played. Because speech is always packaged as speech.vox, we can't play any speech. First reported here: https://www.adventuregamestudio.co.uk/forums/index.php?topic=59772.msg636644240#msg636644240

**AGS Version**
AGS 3.6.0.20 but also current master https://github.com/adventuregamestudio/ags/tree/b8a811f9e939328987af3adbbad7c72617dfbafd

**To Reproduce**
In the editor create a new game
1. add any sound and make sure that it's marked to be in a .vox package instead of being packaged inside the game
2. build for Android in the Editor
3. verify the sound doesn't play

**Expected behavior**
The sound should play

**Desktop:**
 - OS: Windows
 - Version: 10

**Smartphone:**
 - Device: Pixel 2 A
 - OS: Android 11
 - Emulated

**Additional context**
When listing the libraries in AssetManager `_activeLibs`, I can only see the root dir and the game.ags file - the vox package doesn't appear as a library. I can see the game tries to look for the `"/au000004.mp3"` clip but it can't find it in either the ags game or in the root dir. The vox packages apparently can't be found.

In the single game package the files are not in a regular directory, and instead are accessible through the AAssetManager from Android. It appears some logic is missing for the vox packages there, but I am not sure what it's yet.

### PR DESCRIPTION
**Pull request by ericoporto**
android asset manager can't find files when they are preceded by `/` or `./` inside it's packaged asset.

fix #1577 

I placed the path stuff in the path utilities but if you think it's better to be in the android file then I can move too. I have a feeling that there must be some other proprietary ROM format that would have some similar need but I don't know any at the time.

I also named the function that simplifies the path as `GetPathInForeignAsset` to illustrate that the asset in question is not an AGS asset but a ROM type of information that another system also calls as "asset".

### CODE REVIEW

File: Common/util/path.cpp [hunk 1]
```diff
@@ -173,6 +173,28 @@ String FixupSharedFilename(const String &filename)
...
+            String adjusted_filename = filename;
+            adjusted_filename.ClipLeft(1);
+            return adjusted_filename;
+        }
+        else if(filename[0] == '.' && filename[1] == '/')
+        {
+            String adjusted_filename = filename;
+            adjusted_filename.ClipLeft(2);
+            return adjusted_filename;
+        }
```
Comment (ivan-mogilko) [inline Common/util/path.cpp:192]: The shorter code could be
```
if (filename[0] == '/' || (filename.GetLength() > 1 && filename[0] == '.' && filename[1] == '/))
{
    return filename.Section('/', 1, -1);
}
```

File: Common/util/path.cpp [hunk 2]
```diff
@@ -173,6 +173,28 @@ String FixupSharedFilename(const String &filename)
     return fixed_name;
 }
 
+#if AGS_PLATFORM_OS_ANDROID
+    String GetPathInForeignAsset(const String &filename)
+    {
+        if(filename.IsNullOrSpace()) return filename;
```
Comment (ivan-mogilko) [inline Common/util/path.cpp:179]: This is not significant, but in general it's best to use String.IsEmpty(), because it tests for empty string (uninitialized or zero length), while NullOrSpace parses whole string to see if it only contains whitespace chars.

File: Common/util/path.cpp (hunk 1 above)
Comment (ericoporto) [reply Common/util/path.cpp:192]: Curiosity, is the length check needed? If the string is 0 terminated, then it has at least two characters if it's not null or empty. 🤔

File: Common/util/path.cpp (hunk 2 above)
Comment (ericoporto) [reply Common/util/path.cpp:179]: Ah, I mistook what the function did, I did intent for IsEmpty then, I will adjust.

File: Common/util/path.cpp (hunk 1 above)
Comment (ivan-mogilko) [reply Common/util/path.cpp:192]: > Curiosity, is the length check needed? If the string is 0 terminated, then it has at least two characters if it's not null or empty.

That's a good point, the String does do regular test in operator[], but it has `assert` which will trigger in debug config.

Comment (ivan-mogilko) [reply Common/util/path.cpp:192]: That is, right now the String class has this:
```
    inline char operator[](size_t index) const
    {
        assert(index < _len);
        return _cstr[index];
    }
```
May be changed to
```
    inline char operator[](size_t index) const
    {
        assert(index <= _len);
        return _cstr[index];
    }
```

IIRC String class guarantees _cstr is valid at all times, pointing to "" literal if was not initialized.

Comment (ivan-mogilko) [reply Common/util/path.cpp:192]: Actually, this is not way too important, there are various ways to simplify it, one is to use same conditions but avoid creating local variables, example:
```
        if(filename[0] == '/')
        {
            return filename.Left(1);
        }
        else if(filename[0] == '.' && filename[1] == '/')
        {
            return filename.Left(2);
        }
```

Comment (ivan-mogilko) [reply Common/util/path.cpp:192]: Actually, there are various ways to simplify this, one way to keep same conditions but only avoid creating local variables:
```
        if(filename[0] == '/')
        {
            return filename.Mid(1);
        }
        else if(filename[0] == '.' && filename[1] == '/')
        {
            return filename.Mid(2);
        }
```

Maybe it's the best one.
`Mid` acts like normal "substring".

Comment (ericoporto) [reply Common/util/path.cpp:188]: I went with this last suggestion! Pushed below!
