### PR TITLE
Engine: fix touch events not working in iOS Safari

### LINKED ISSUE #1954: Web Port in iOS Safari doesn't register clicks
**Describe the bug**
When running our Web port in the iOS Safari browser, clicks are not registered

The reason it appears to be that [Touch.identifier](https://developer.mozilla.org/en-US/docs/Web/API/Touch/identifier) works differently in it.

Here is a log after I added three log functions in sys_events.cpp, this is in a simulator, so the mouse is only one finger, I click, move and release I think six times and get this.

```
[Log] 20:31:36:062: on_sdl_touch_down: fingerId 998779017, xy (0.611224, 0.570836), dxdy (0.000000, 0.000000); (tst, line 583)
[Log] 20:31:36:096: on_sdl_touch_motion: fingerId 998779017, xy (0.611224, 0.570243), dxdy (0.000000, -0.000593); (tst, line 583)
[Log] 20:31:36:151: on_sdl_touch_up: fingerId 998779017, xy (0.611224, 0.570243), dxdy (0.000000, 0.000000); (tst, line 583)
[Log] 20:31:39:831: on_sdl_touch_down: fingerId 998779018, xy (0.586735, 0.581506), dxdy (0.000000, 0.000000); (tst, line 583)
[Log] 20:31:39:895: on_sdl_touch_motion: fingerId 998779018, xy (0.586735, 0.580913), dxdy (0.000000, -0.000593); (tst, line 583)
[Log] 20:31:39:948: on_sdl_touch_up: fingerId 998779018, xy (0.586735, 0.580913), dxdy (0.000000, 0.000000); (tst, line 583)
[Log] 20:31:51:444: on_sdl_touch_down: fingerId 998779019, xy (0.518367, 0.548903), dxdy (0.000000, 0.000000); (tst, line 583)
[Log] 20:31:51:485: on_sdl_touch_motion: fingerId 998779019, xy (0.518367, 0.548311), dxdy (0.000000, -0.000593); (tst, line 583)
[Log] 20:31:51:485: on_sdl_touch_up: fingerId 998779019, xy (0.518367, 0.548311), dxdy (0.000000, 0.000000); (tst, line 583)
[Log] 20:32:49:277: on_sdl_touch_down: fingerId 998779020, xy (0.271429, 0.595732), dxdy (0.000000, 0.000000); (tst, line 583)
[Log] 20:32:49:278: on_sdl_touch_motion: fingerId 998779020, xy (0.271429, 0.594547), dxdy (0.000000, -0.001186); (tst, line 583)
[Log] 20:32:49:278: on_sdl_touch_motion: fingerId 998779020, xy (0.275510, 0.594547), dxdy (0.004082, 0.000000); (tst, line 583)
[Log] 20:32:49:321: on_sdl_touch_motion: fingerId 998779020, xy (0.303061, 0.594547), dxdy (0.027551, 0.000000); (tst, line 583)
[Log] 20:32:49:323: on_sdl_touch_motion: fingerId 998779020, xy (0.488776, 0.598103), dxdy (0.185714, 0.003557); (tst, line 583)
[Log] 20:32:49:389: on_sdl_touch_motion: fingerId 998779020, xy (0.518367, 0.597510), dxdy (0.029592, -0.000593); (tst, line 583)
[Log] 20:32:49:389: on_sdl_touch_motion: fingerId 998779020, xy (0.544898, 0.596918), dxdy (0.026531, -0.000593); (tst, line 583)
[Log] 20:32:49:439: on_sdl_touch_motion: fingerId 998779020, xy (0.550000, 0.596918), dxdy (0.005102, 0.000000); (tst, line 583)
[Log] 20:32:49:822: on_sdl_touch_up: fingerId 998779020, xy (0.550000, 0.596918), dxdy (0.000000, 0.000000); (tst, line 583)
[Log] 20:32:54:715: on_sdl_touch_down: fingerId 998779021, xy (0.225510, 0.544754), dxdy (0.000000, 0.000000); (tst, line 583)
[Log] 20:32:54:773: on_sdl_touch_motion: fingerId 998779021, xy (0.225510, 0.543568), dxdy (0.000000, -0.001186); (tst, line 583)
[Log] 20:32:54:871: on_sdl_touch_motion: fingerId 998779021, xy (0.225510, 0.542976), dxdy (0.000000, -0.000593); (tst, line 583)
[Log] 20:32:55:072: on_sdl_touch_motion: fingerId 998779021, xy (0.253061, 0.553646), dxdy (0.027551, 0.010670); (tst, line 583)
[Log] 20:32:55:073: on_sdl_touch_motion: fingerId 998779021, xy (0.277551, 0.561944), dxdy (0.024490, 0.008299); (tst, line 583)
[Log] 20:32:55:126: on_sdl_touch_motion: fingerId 998779021, xy (0.318367, 0.573800), dxdy (0.040816, 0.011855); (tst, line 583)
[Log] 20:32:55:126: on_sdl_touch_motion: fingerId 998779021, xy (0.371429, 0.587433), dxdy (0.053061, 0.013634); (tst, line 583)
[Log] 20:32:55:169: on_sdl_touch_motion: fingerId 998779021, xy (0.404082, 0.593954), dxdy (0.032653, 0.006520); (tst, line 583)
[Log] 20:32:55:170: on_sdl_touch_motion: fingerId 998779021, xy (0.441837, 0.602845), dxdy (0.037755, 0.008892); (tst, line 583)
[Log] 20:32:55:253: on_sdl_touch_motion: fingerId 998779021, xy (0.468367, 0.606995), dxdy (0.026531, 0.004149); (tst, line 583)
[Log] 20:32:55:254: on_sdl_touch_motion: fingerId 998779021, xy (0.512245, 0.611144), dxdy (0.043878, 0.004149); (tst, line 583)
[Log] 20:32:55:307: on_sdl_touch_motion: fingerId 998779021, xy (0.525510, 0.611737), dxdy (0.013265, 0.000593); (tst, line 583)
[Log] 20:32:55:307: on_sdl_touch_motion: fingerId 998779021, xy (0.534694, 0.611737), dxdy (0.009184, 0.000000); (tst, line 583)
[Log] 20:32:55:580: on_sdl_touch_up: fingerId 998779021, xy (0.534694, 0.611737), dxdy (0.000000, 0.000000); (tst, line 583)
```

**AGS Version**
it happens on current 3.6.0.45, but curiously it did not happen in an old version.

**Game**
https://ericoporto.github.io/agsjs/tst/

**To Reproduce**
1. Load the URL and see that touching the screen does nothing.
2. If you have Safari Technology Preview installed on a macOS you can connect to the iOS system with Safari
3. the log will have the mentioned on_sdl_touch log messages

**Expected behavior**
It's expected to work

**Smartphone:**
 - Device: iOS Simulator with iPhone 14 Pro Max
 - OS: iOS
 - Version 16.2

**Additional context**
When SDL own touch emulation was used, there was no reliance in fingerId, so it worked with that.

The API from SDL only states that fingerId is unique, and nothing else, so apparently we can't rely on actual values from it - even though on Android it's consistent with both the App and the Web version on different browsers, it appears on other devices this is not guaranteed.

### PR DESCRIPTION
**Pull request by ericoporto**
fix #1954

FingerContainer is probably not a good name, and I guess it could be more efficient, but I don't expect the number of fingers to be more than one digit ever, so I think this should work fast enough.

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
> but I don't expect the number of fingers to be more than one digit ever

Actually, for this reason, I wanted to suggest to not use any containers, but use a plain array of fixed size.
In the current implementation, having std::map looks redundant, as you are searching it as a plain array/vector anyway, and use `find` only in one case.

Other than that, I'd like to ask to not sequence all the commands in one line like this:
```
for(; idx < _fingers.size(); idx++) if(_fingers.count(idx) == 0) break;
```
Imo that makes it difficult to read; and contradicts to our code style in general.
```
for (; idx < _fingers.size(); idx++)
    if (_fingers.count(idx) == 0)
        break;
```

**Comment by ericoporto** [comment]
> The size is the number of simultaneous touches that we care about (two currently)

I can do 20, if I do 2 the logic will crumble once a person puts a third finger in the screen, people have ten fingers, 20 seems safe.

**Comment by ivan-mogilko** [comment]
> if I do 2 the logic will crumble once a person puts a third finger in the screen

Could you explain? Maybe I cannot imagine the problem myself.

**Comment by ericoporto** [comment]
I am not sure I understand how that fingers_down should work, but I thought it was like a bitfield where the first finger is first bit, second finger is second bit and so on, so if I place an "invalid" finger, I don't know what to return there, and also I need to now ignore this invalid finger in all the other two cases (motion/up). If I simply support more fingers (up to 31), things kinda just work.

**Comment by ivan-mogilko** [comment]
Hmm, I thought `fingers_down` could be removed actually, or even made a part of this FingerContainer. But iirc at the moment this bit field is not used as bit field, but strictly to count number of fingers (0, 1, >1). So if you remove it and replace with "get finger count", that should work for now.

>  so if I place an "invalid" finger, I don't know what to return there, and also I need to now ignore this invalid finger in all the other two cases (motion/up).

Maybe it will work if you don't place any "invalid" fingers at all, and ignore them. So, let's say, you receive a touch up / motion event, check whether this finger is in FingerContainer, and if not, just bail.

**Comment by ericoporto** [comment]
https://github.com/adventuregamestudio/ags/pull/1955#issuecomment-1475356629

I haven't added comments yet or tried to move fingers_down into the container, but overall, did a bit of refactor there

> Maybe it will work if you don't place any "invalid" fingers at all,

I am trying this idea in the commit: [SKETCH deal with invalid fingers](https://github.com/adventuregamestudio/ags/pull/1955/commits/c2e335fc4076177f4e2bda4703ca52099728f20c)

**Comment by ericoporto** [comment]
I think I can squash all of these in a single commit, it is working in my tests, just let me know and I will do so.

**Comment by ericoporto** [comment]
Hey, I squashed the commits. The previous individual commits are kept here: https://github.com/ericoporto/ags/tree/fix-web-ios-touch-old

**Comment by ivan-mogilko** [comment]
Yes, I think that may work nicely, I just may have few nitpicks about the code...

File: Engine/ac/sys_events.cpp [hunk 1]
```diff
@@ -498,9 +498,66 @@ int ags_check_mouse_wheel() {
...
+    static const int MAX_FINGERS = 2;
+    static const int NO_ID = -1;
+
+    void push(SDL_FingerID fingerId)
+    {
+        if (contains(fingerId))
+            return;
+
+        for (int i = 0; i < MAX_FINGERS; i++) {
+            if (_fingers[i] == NO_ID) {
```
Comment (ivan-mogilko) [inline Engine/ac/sys_events.cpp:521]: I think this may be replaced with `std::find(_fingers.begin(), _fingers.end(), NO_ID)`. If result is _finder.end(), then there's no slot for a new finger, otherwise `*it = fingerId;` will set a finger id in place.

File: Engine/ac/sys_events.cpp [hunk 2]
```diff
@@ -498,9 +498,66 @@ int ags_check_mouse_wheel() {
...
+                _fingers[i] = fingerId;
+                return;
+            }
+        }
+    };
+
+    int get_index(SDL_FingerID fingerId) const
+    {
+        for(int i=0; i < MAX_FINGERS; i++) {
+            if(_fingers[i] == fingerId)
```
Comment (ivan-mogilko) [inline Engine/ac/sys_events.cpp:531]: Same as above, this may be replaced with std::find(_fingers.begin(), _fingers.end(), fingerId)

File: Engine/ac/sys_events.cpp [hunk 3]
```diff
@@ -678,7 +737,11 @@ static void sync_sys_mouse_pos()
 
 static void on_sdl_touch_down(const SDL_TouchFingerEvent &event)
 {
-    touch.fingers_down |= 1 << event.fingerId;
+    touch.fingers.push(event.fingerId);
+    int finger_index = touch.fingers.get_index(event.fingerId);
```
Comment (ivan-mogilko) [inline Engine/ac/sys_events.cpp:741]: If you make `push` return a new index, then you can save on 1 function call here, that is
```int finger_index = touch.fingers.push(event.fingerId);```

File: Engine/ac/sys_events.cpp [hunk 4]
```diff
@@ -794,10 +860,14 @@ static void on_sdl_touch_up(const SDL_TouchFingerEvent &event)
     }
     default: break; // do nothing
     }
+    touch.fingers.pop(event.fingerId);
 }
 
 static void on_sdl_touch_motion(const SDL_TouchFingerEvent &event)
 {
+    int finger_index = touch.fingers.get_index(event.fingerId);
```
Comment (ericoporto) [inline Engine/ac/sys_events.cpp:868]: Do you have thoughts on `tfinger_to_mouse_but` using finger_index instead of fingerId? If it used finger_index then I don't need to ask for it again inside of it.

File: Engine/ac/sys_events.cpp (hunk 3 above)
Comment (ericoporto) [reply Engine/ac/sys_events.cpp:741]: If I do this, then I don't think I should do the iterator thing you suggested inside the push call, because then I need to calculate a distance to extract the index from the iterator.

File: Engine/ac/sys_events.cpp (hunk 2 above)
Comment (ericoporto) [reply Engine/ac/sys_events.cpp:531]: how do I return the index using this?

Comment (ivan-mogilko) [reply Engine/ac/sys_events.cpp:531]: > how do I return the index using this?

`it - _fingers.begin()`

File: Engine/ac/sys_events.cpp (hunk 3 above)
Comment (ivan-mogilko) [reply Engine/ac/sys_events.cpp]: I was thinking about this:
```
    int push(SDL_FingerID fingerId)
    {
        if (contains(fingerId))
            return NO_ID;

        auto it = std::find(_fingers.begin(), _fingers.end(), NO_ID);
        if (it == _fingers.end()) return NO_ID;
        *it = fingerId;
        return it - _fingers.begin();
    };
```

File: Engine/ac/sys_events.cpp (hunk 2 above)
Comment (ericoporto) [reply Engine/ac/sys_events.cpp]: ok, I tried to do this in the sketch commit below

File: Engine/ac/sys_events.cpp (hunk 4 above)
Comment (ivan-mogilko) [reply Engine/ac/sys_events.cpp:861]: Oh, sure.

Comment (ericoporto) [reply Engine/ac/sys_events.cpp:861]: OK, I added this in the commit below

File: Engine/ac/sys_events.cpp (hunk 3 above)
Comment (ericoporto) [reply Engine/ac/sys_events.cpp]: ok, so, imagining if two touch down occurred in sequence, the idea here is to dismiss one of them

Comment (ivan-mogilko) [reply Engine/ac/sys_events.cpp]: >  imagining if two touch down occurred in sequence, the idea here is to dismiss the second

Could you elaborate, I don't quite understand this?

Comment (ericoporto) [reply Engine/ac/sys_events.cpp]: well, theoretically, that contain clause is there as a safety, but we should not need it. But in case the system misbehaves and we get two touch down before an up, using the same fingerId, then the second touch down is ignored. I think this is the correct behavior btw, so I agree with your code change.

**Comment by ericoporto** [comment]
I think I can squash the commits now, the std::find showed I was mixing types for index and SDL_FingerID, so I fixed that.

**Comment by ivan-mogilko** [comment]
Yes, i think this turned out nice, as all changes are contained in "index conversion" step, and the rest of logic remains.

**Comment by ericoporto** [comment]
Apparently std::find can read by reference and on some compilers  this fails when the value it's looking is a static const, I removed the static qualifier and it appears to work locally. Please wait the CI to make sure it all actually builds.
